version: '3'
services:
  reverse-proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: always
    depends_on:
      - pocketbase
  pocketbase:
    build:
      context: ./pocketbase  
    # Add your app configuration here